---
title: "R Notebook"
output: html_notebook
---



```{r packages}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(viridis)
require(here)
require(janitor)


```

```{r readfiles}
df <- read.csv('dummydata.csv')
myjisc <- read.csv('survey_template.csv')
jisccodes <- seq(4,36,2) #X Codes in JISC file corresponding to items

names(df)<-substring(names(df),1,12) #shorten df names to 12 chars
names(df)[2:3]<-c('ID','group')
df<-clean_names(df)
ncases <- 90
df[1:ncases,1]<-NA

```

```{r simulatedata}
#simulate group ID
ngroup <- 3
df$group<-sample(1:ngroup,ncases,replace=TRUE)
df$id<-sample(1001:2000,ncases,replace=FALSE)

#For each item we use the items data to find how many options there are, and what the response range is. We then simulate responses.

njisc<-nrow(myjisc)
for (i in 1:njisc){
  nopt <- myjisc$N.options[i]
  topopt <- myjisc$hirange[i]
  itemcode<-paste0('x',jisccodes[i],'_')
  w<- grep(itemcode,names(df))
  if(nopt>1){
    w<-w[-1] #omit first number if more than one options; first is introtext
  }
  for (ww in w)
    df[,ww]<-sample(1:topopt,ncases,replace=TRUE)
}

#NB for items with single multiple choice, I have simulated with numeric data. These are recorded on JISC file as text, so will need converting

df<-df[order(df$group),] #cluster group members together

```


```{r doroundplot}
#Used code from https://bookdown.org/content/b298e479-b1ab-49fa-b83d-a57c2b034d49/part.html#circular-stacked-barchart

doround <- function(data,nopt,nitem){
  empty_bar <- 2
  nObsType <- nlevels(as.factor(data$response))
  to_add <- data.frame( matrix(NA, empty_bar*nlevels(data$group)*nObsType, ncol(data)) )
  colnames(to_add) <- colnames(data)
  to_add$group <- rep(levels(data$group), each=empty_bar*nObsType )
  data <- rbind(data, to_add)
  data <- data %>% arrange(group)
  data$id <- rep( seq(1, nrow(data)/nObsType) , each=nObsType)
  
  label_data <-aggregate(data$response,by=list(data$item,data$group,data$response),FUN=length,drop=FALSE)
  names(label_data)<-c('item','group','response','count')
  
  nblock <-round(nrow(label_data)/ngroup,0)
  
  #now insert blank rows between groups: this is fiddly!
  range1<-1:nblock
  range2<-nblock+(1:nblock)
  range3<-nblock+range2
  plotdata<-rbind(label_data[range1,],label_data[1,])
  plotdata<-rbind(plotdata,label_data[range2,],label_data[1,])
  plotdata<-rbind(plotdata,label_data[range3,],label_data[1,])
  myrows<-c(range2[1],(1+range3[1]),nrow(plotdata))
  for (k in myrows){
    for (j in 1:ncol(plotdata)){
      plotdata[k,j]<-NA
    }
  }
  plotdata$count[myrows]<-0
  plotdata$group[myrows]<-unique(plotdata$group)
  plotdata$response[myrows]<-1
  plotdata$item[myrows]<-'_'
  plotdata$x <- as.factor(paste0(plotdata$group,"_",plotdata$item))
  label_data$x<-as.factor(paste0(label_data$group,"_",label_data$item))
  #x is variable denoting conjunction of group and item
  
  plotdata$response<-as.factor(plotdata$response)
  
  #Plotting starts here. 
  endx <- (nopt+1) #end xvalue for each group
  p <- ggplot(plotdata) +      
    
    # Add the stacked bar
    
    geom_bar(aes(x=x, y=count, fill=response), stat="identity", alpha=0.5) +
    scale_fill_viridis(discrete=TRUE) +
    theme_bw() +
    theme(
      #legend.position = "none",
      legend.title=element_text(size=10),
      legend.text=element_text(size=10),
      axis.text = element_blank(),
      axis.title = element_blank(),
      panel.grid = element_blank(),
      #plot.margin = unit(rep(-1,4), "cm") 
    )+
    #crucial to position annotations before convert to polar
    annotate("text",label="Group 1",x=(endx*.6),y = 36)+
    annotate("text",label="Group 2",x=(endx+(endx*.6)),y = 36)+
    annotate("text",label="Group 3",x=(2*endx+(endx*.6)),y = 36)+
    # Add labels on top of each bar - again - do this before polar step
    geom_text(data=label_data, aes(x=x, y=-5, label=item), color="black",size=4) 
  
  # coord_polar()+ 
  # ylim(-20,100)
  filename<-paste0("plot_jiscitem_",i,".png")
  ggsave(p, file=filename, width=8, height=6)
  return()
}

```

```{r loopbit}
njisc<-nrow(myjisc)
for (i in 1:njisc){
  nopt <- myjisc$N.options[i]
  itemcode<-paste0('x',jisccodes[i],'_')
  w<- grep(itemcode,names(df))
  if(nopt>1){
    w<-w[-1] #omit first number if more than one options; first is introtext
    
    datax <- df[,c(2,3,w)]
    names(datax)[3:ncol(datax)]<-LETTERS[1:nopt]
    data <- datax %>% gather(key = "item", value="response", -c(1,2)) #long form for this item
    nitem<-1
    p<-doround(data,nopt,nitem = ) #call plotting function
  }
  if(nopt==1){
    #present results in a table for single option items
    mytab <- aggregate(df[,w],by=list(df$group,df[,w]),FUN=length,drop=FALSE)
    mytab <- table(df[,w],df$group)
    myt <- as.data.frame.matrix(mytab)
    names(myt)<-c('Group1','Group2','Group3')
    ww<-which(names(myjisc)=='introtext')
    rownames(myt)<-myjisc[i,(ww+1):(ww+myjisc$hirange[i])]
    knitr::kable(myt)
  }
    
}

```


